

services:
  frontend:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    ports:
      - "8002:8002"
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    ports:
      - "8003:8003"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge

